# @package _global_

defaults:  
  - default
  - override /logger@_group_: wandb
  - override /hydra/hydra_logging@_group_: colorlog
#   - override /hydra/job_logging@_group_: none 
  
# task_name: "debug"


# hydra:  
#   output_subdir: null  
#   run:  
#     dir: .

