#############################################
################## Paths ####################
#############################################
paths:
  # path to root directory
  # this requires PROJECT_ROOT environment variable to exist
  root_dir: ${oc.env:PROJECT_ROOT}

  # path to data directory
  data_dir: ${paths.root_dir}/data

  # path to logging directory
  log_dir: ${paths.root_dir}/logs

  # path to checkpoints directory
  ckpt_dir: ${paths.root_dir}/checkpoints

  # path to output directory, created dynamically by hydra
  # path generation pattern is specified in `configs/hydra/default.yaml`
  # use it to store all files generated during the run, like ckpts and metrics
  output_dir: ${hydra:runtime.output_dir}

  # path to working directory
  work_dir: ${hydra:runtime.cwd}

#############################################
############## Hydra configs ################
#############################################
hydra:
  # enable color logging
  defaults:
    - override hydra_logging: colorlog
    - override job_logging: colorlog
    - _self_

  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

  # output directory, generated dynamically on each run
  run:
    dir: ${paths.log_dir}/${task_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${paths.log_dir}/${task_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}

#############################################
############## Wandb configs ################
#############################################
wandb:
  # name: "" # name of the run (normally generated by wandb and can be changed afterward)
  dir: ${paths.output_dir}
  mode: "online"
  id: null # pass correct id to resume experiment!
  anonymous: null # enable anonymous logging
  project: "preset-embedding_audio-model-selection"
  # group: ${model.name}
  tags: []
